# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ v1.x ]
  pull_request:
    branches: [ v1.x ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: windows-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - uses: s4u/maven-settings-action@v2.3.0
      with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.GITHUB_USERNAME }}",
                "password": "${{ secrets.GITHUB_PASSWORD }}"
            }]
          repositories: |
            [{
                "repository": {
                    "id": "github",
                    "name": "GitHub williamniemiec Apache Maven Packages",
                    url: "https://maven.pkg.github.com/williamniemiec/utils/"
                }
            }]
    - name: Build with Maven
      run: mvn install
  
